version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

    groups:
      drizzle:
        patterns:
          - drizzle-orm

      testing:
        patterns:
          - vitest
          - "@vitest/*"

      web-toolchain:
        patterns:
          - vite
          - "@vitejs/*"
          - react
          - react-dom
          - "@types/react*"
